/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dark: typeof import('./components/Dark.vue')['default']
    Emulator: typeof import('./components/Emulator/index.vue')['default']
    Moment: typeof import('./components/Wechat/Moment.vue')['default']
    Phone: typeof import('./components/Phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    WechatForm: typeof import('./components/Wechat/WechatForm.vue')['default']
    WechatImages: typeof import('./components/Wechat/WechatImages.vue')['default']
    WechatMoment: typeof import('./components/Wechat/WechatMoment.vue')['default']
    WechatPostItem: typeof import('./components/Wechat/WechatPostItem.vue')['default']
    WechatPostList: typeof import('./components/Wechat/WechatPostList.vue')['default']
    WechatStatusBar: typeof import('./components/Wechat/WechatStatusBar.vue')['default']
    WechatTextContent: typeof import('./components/Wechat/WechatTextContent.vue')['default']
  }
}
